openapi: 3.1.0
info:
  version: 1.0.0
  title: AyatDigital Open API Spec
  servers:
  - url: https://dev.ayatdigital.com
  - url: https://example.com/api/v1
paths:
  /events:
    get:
      operationId: GetAllEvents
      tags:
        - Event
      summary: Get all events
      description: Get all events from the database
      parameters:
        - name: pageNumber
          in: query
          description: The pages to return events information
          schema:
            type: integer
          required: false
        - name: pageSize
          in: query
          description: The number of events to be returned in a page
          schema:
            type: integer
            example: 9
          required: false
      responses:
        '200':
          description: Fetched all events successfully
          content:
            application/json:
              schema:
                properties:
                  events:
                    type: array
                    items:
                      description: model containing event information
                      properties:
                        id:
                          type: integer
                          example: 1
                  total_events:
                    description: Total number of events stored in the database
                    type: integer
                    example: 1
        '404':
          description: Not Found
        '503':
          description: Server Error
